name: marketing-automation

on:
  workflow_dispatch:
  schedule:
    - cron: '15 14 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Crawl audit
        continue-on-error: true
        run: python tasks/crawl_audit.py

      - name: Build sitemap
        run: python tasks/sitemap_build.py

      - name: Upload sitemap via FTPS
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: 21
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          REMOTE_SITEMAP_PATH: /public_html/sitemap.xml
        run: python tasks/upload_sitemap_ftps.py

      - name: Ping Google/Bing
        run: |
          curl -s -o /dev/null -w "Google ping: %{http_code}\n" "https://www.google.com/ping?sitemap=https://www.packntec.com/sitemap.xml"
          curl -s -o /dev/null -w "Bing ping:   %{http_code}\n" "https://www.bing.com/ping?sitemap=https://www.packntec.com/sitemap.xml"

      - name: Upload reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
