name: marketing-automation

on:
  workflow_dispatch:
  schedule:
    - cron: "15 14 * * *"  # daily 14:15 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Crawl audit
        run: python tasks/crawl_audit.py

      - name: Build sitemap
        run: python tasks/sitemap_build.py

      - name: Upload sitemap via SFTP (if secrets present)
        env:
         SFTP_HOST: ${{ secrets.SFTP_HOST }}
         SFTP_PORT: ${{ secrets.SFTP_PORT }}
         SFTP_USER: ${{ secrets.SFTP_USER }}
         SFTP_PASS: ${{ secrets.SFTP_PASS }}
         REMOTE_SITEMAP_PATH: /home/z09esrwccxu0/public_html/sitemap.xml
        run: python tasks/upload_sitemap.py

      - name: Ping Google/Bing
        run: |
          curl -s -o /dev/null -w "Google ping: %{http_code}\n" "https://www.google.com/ping?sitemap=https://www.packntec.com/sitemap.xml"
          curl -s -o /dev/null -w "Bing ping:   %{http_code}\n" "https://www.bing.com/ping?sitemap=https://www.packntec.com/sitemap.xml"

      - name: Upload reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**

