name: marketing-automation

on:
  workflow_dispatch:
  schedule:
    - cron: "15 14 * * *"  # daily 14:15 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Crawl audit
        run: python tasks/crawl_audit.py

      - name: Build sitemap
        run: python tasks/sitemap_build.py

      - name: Upload sitemap via SFTP (if secrets present)
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
        shell: bash
        run: |
          if [[ -n "${SFTP_HOST}" && -n "${SFTP_USER}" && -n "${SFTP_PASS}" ]]; then
            python - <<'PY'
from utils.sftp import sftp_upload
local = "reports/sitemap.xml"
remote = "/home/z09esrwccxu0/public_html/sitemap.xml"  # <-- change this
print("Uploading", local, "to", remote)
sftp_upload(local, remote)
print("Sitemap uploaded.")
PY
          else
            echo "SFTP secrets not set; skipping upload."
          fi

      - name: Ping Google/Bing
        shell: bash
        run: |
          curl -s -o /dev/null -w "Google ping: %{http_code}\n" "https://www.google.com/ping?sitemap=https://www.packntec.com/sitemap.xml"
          curl -s -o /dev/null -w "Bing ping:   %{http_code}\n" "https://www.bing.com/ping?sitemap=https://www.packntec.com/sitemap.xml"

      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
